--backup sql, XXXX should be the date when realease this Script.
CREATE TABLE case_XXXX AS SELECT * FROM CASE;


---backout sql
MERGE INTO CASE C
USING (SELECT CB.*
       FROM   CASE C, CASE_XXXX CB
       WHERE  CB.CASE_ID = C.CASE_ID
       AND    CB.CURRENT_STATUS_ID <> C.CURRENT_STATUS_ID) T
ON (C.CASE_ID = T.CASE_ID)
WHEN MATCHED THEN
  UPDATE SET C.CURRENT_STATUS_ID = T.CURRENT_STATUS_ID;
